// build-env.js - Used in GitHub Actions to inject environment variables
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Read environment variables
const apiKey = process.env.VITE_GOOGLE_DRIVE_API_KEY || '';
const clientId = process.env.VITE_GOOGLE_DRIVE_CLIENT_ID || '';

// Create .env file
const envContent = `# Generated by build-env.js
VITE_GOOGLE_DRIVE_API_KEY=${apiKey}
VITE_GOOGLE_DRIVE_CLIENT_ID=${clientId}
`;

const envPath = path.join(__dirname, '.env');

try {
    fs.writeFileSync(envPath, envContent);
    console.log('✅ Environment file generated successfully');
    console.log(`📁 Location: ${envPath}`);
    console.log(`🔐 API Key configured: ${apiKey ? '✅ Yes' : '❌ No'}`);
    console.log(`🔐 Client ID configured: ${clientId ? '✅ Yes' : '❌ No'}`);
} catch (error) {
    console.error('❌ Failed to generate environment file:', error.message);
    process.exit(1);
}
